services:
  web:
    build: .
    container_name: php-dev-server
    volumes:
      - ./salonhub:/var/www/html
    ports:
      - "8080:80"
    privileged: true
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data